-- 8.1 HOSPITAL Table
CREATE TABLE HOSPITAL (
    HospitalID INT PRIMARY KEY IDENTITY(1,1),
    HospitalName VARCHAR(100) NOT NULL,
    Address VARCHAR(255),
    Phone VARCHAR(20),
    RegistrationNo VARCHAR(50) UNIQUE NOT NULL
);

-- 8.2 BRANCH Table
CREATE TABLE BRANCH (
    BranchID INT PRIMARY KEY IDENTITY(1,1),
    BranchName VARCHAR(100) NOT NULL,
    Address VARCHAR(255),
    HospitalID INT NOT NULL,
    FOREIGN KEY (HospitalID) REFERENCES HOSPITAL (HospitalID)
);

-- 8.3 DEPARTMENT Table
CREATE TABLE DEPARTMENT (
    DeptID INT PRIMARY KEY IDENTITY(1,1),
    DeptName VARCHAR(100) NOT NULL,
    DeptHead VARCHAR(100),
    BranchID INT NOT NULL,
    FOREIGN KEY (BranchID) REFERENCES BRANCH (BranchID)
);

-- 8.4 DOCTOR Table
CREATE TABLE DOCTOR (
    DoctorID INT PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Specialization VARCHAR(100),
    LicenseNo VARCHAR(50) UNIQUE NOT NULL,
    DeptID INT NOT NULL,
    ConsultFee DECIMAL(10,2),
    FOREIGN KEY (DeptID) REFERENCES DEPARTMENT (DeptID)
);

-- 8.5 PATIENT Table
CREATE TABLE PATIENT (
    PatientID INT PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    DOB DATE,
    Gender CHAR(1),
    NIC VARCHAR(15) UNIQUE NOT NULL,
    ContactNo VARCHAR(15),
    BloodGroup VARCHAR(5)
);

-- 8.6 APPOINTMENT Table
CREATE TABLE APPOINTMENT (
    AppointmentID INT PRIMARY KEY IDENTITY(1,1),
    PatientID INT NOT NULL,
    DoctorID INT NOT NULL,
    BranchID INT NOT NULL,
    AppDate DATE NOT NULL,
    AppTime TIME,
    Status VARCHAR(20) DEFAULT 'Scheduled',
    FOREIGN KEY (PatientID) REFERENCES PATIENT (PatientID),
    FOREIGN KEY (DoctorID) REFERENCES DOCTOR (DoctorID),
    FOREIGN KEY (BranchID) REFERENCES BRANCH (BranchID)
);

-- 8.7 PRESCRIPTION Table
CREATE TABLE PRESCRIPTION (
    PrescriptionID INT PRIMARY KEY IDENTITY(1,1),
    AppointmentID INT NOT NULL UNIQUE,
    PrescribedDate DATE NOT NULL,
    Status VARCHAR(20) DEFAULT 'Active',
    PharmacistID INT,
    FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT (AppointmentID)
);

-- 8.8 MEDICINE Table
CREATE TABLE MEDICINE (
    MedicineID INT PRIMARY KEY IDENTITY(1,1),
    MedicineName VARCHAR(100) NOT NULL,
    GenericName VARCHAR(100),
    CategoryID INT,
    UnitPrice DECIMAL(10,2),
    ReorderLevel INT DEFAULT 10,
    DosageForm VARCHAR(50),
    Strength VARCHAR(50)
);

-- 8.9 INVENTORY Table
CREATE TABLE INVENTORY (
    InventoryID INT PRIMARY KEY IDENTITY(1,1),
    BranchID INT NOT NULL,
    MedicineID INT NOT NULL,
    BatchNo VARCHAR(50),
    Quantity INT NOT NULL DEFAULT 0,
    ExpiryDate DATE,
    CostPrice DECIMAL(10,2),
    FOREIGN KEY (BranchID) REFERENCES BRANCH (BranchID),
    FOREIGN KEY (MedicineID) REFERENCES MEDICINE (MedicineID)
);

-- 8.10 SUPPLIER Table
CREATE TABLE SUPPLIER (
    SupplierID INT PRIMARY KEY IDENTITY(1,1),
    SupplierName VARCHAR(100) NOT NULL,
    ContactPerson VARCHAR(100),
    Phone VARCHAR(20),
    Email VARCHAR(100)
);

-- 8.11 PURCHASE_ORDER Table
CREATE TABLE PURCHASE_ORDER (
    POID INT PRIMARY KEY IDENTITY(1,1),
    BranchID INT NOT NULL,
    SupplierID INT NOT NULL,
    OrderDate DATE NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    TotalAmount DECIMAL(12,2),
    FOREIGN KEY (BranchID) REFERENCES BRANCH (BranchID),
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER (SupplierID)
);

-- 8.12 PO_ITEM Table
CREATE TABLE PO_ITEM (
    POItemID INT PRIMARY KEY IDENTITY(1,1),
    POID INT NOT NULL,
    MedicineID INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10,2),
    FOREIGN KEY (POID) REFERENCES PURCHASE_ORDER (POID),
    FOREIGN KEY (MedicineID) REFERENCES MEDICINE (MedicineID)
);

-- 8.13 BILL Table
CREATE TABLE BILL (
    BillID INT PRIMARY KEY IDENTITY(1,1),
    AppointmentID INT NOT NULL UNIQUE,
    BillDate DATE NOT NULL,
    ConsultFee DECIMAL(10,2),
    MedicineFee DECIMAL(10,2),
    TotalAmount DECIMAL(12,2),
    PaymentStatus VARCHAR(20) DEFAULT 'Pending',
    FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT (AppointmentID)
);

-- 8.14 ROLE Table
CREATE TABLE ROLE (
    RoleID INT PRIMARY KEY IDENTITY(1,1),
    RoleName VARCHAR(50) NOT NULL,
    AccessLevel INT DEFAULT 1
);

-- 8.15 STAFF Table
CREATE TABLE STAFF (
    StaffID INT PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    RoleID INT NOT NULL,
    BranchID INT NOT NULL,
    FOREIGN KEY (RoleID) REFERENCES ROLE (RoleID),
    FOREIGN KEY (BranchID) REFERENCES BRANCH (BranchID)
);