CREATE FUNCTION fn_GetPatientAge (@PatientID INT)
RETURNS INT
AS
BEGIN
    DECLARE @Age INT;
    SELECT @Age = DATEDIFF(YEAR, DOB, GETDATE()) FROM PATIENT WHERE PatientID = @PatientID;
    RETURN @Age;
END;
GO